General:
  stats_tracking_enabled: true
  update_check_enabled: true
Soulbound:
  Allow_Item_Drop: true
  Allow_Item_Storing: true
  Delete_On_Death: false
  Keep_On_Death: false
DiabloDrops:
  BindOnPickup: Legendary, Rare, Unidentified
  BindOnUse: Magical
  BindOnEquip: Set