name: Soulbound
author: TfT_02
main: com.me.tft_02.soulbound.Soulbound
description: Soulbound items for your RPG servers!
version: 1.0.0
commands:
   soulbound:
      description: Usage /soulbound
      permission: soulbound.commands
      permission-message: You don't have <permission>
   bind:
      description: Usage /bind
      alias: bound
      permission: soulbound.commands.bind
      permission-message: You don't have <permission>
   bindonpickup:
      description: Usage /bindonpickup
      permission: soulbound.commands.bindonpickup
      permission-message: You don't have <permission>   
   unbind:
      description: Usage /unbind
      alias: unbound
      permission: soulbound.commands.unbind
      permission-message: You don't have <permission>
permissions:
    soulbound.commands.all:
        description: Gives access to the weather commands
        default: op
        children:
            soulbound.commands.bind: true
            soulbound.commands.unbind: true
            soulbound.updatecheck: true
    soulbound.updatecheck:
        description: Users with this permission will receive a notification when there is a new version available.
        default: op