General:
  stats_tracking_enabled: true
  update_check_enabled: true
Soulbound:
  Allow_Item_Drop: true
  Allow_Item_Storing: true
  Infinite_Durability: false
Dependency_Plugins:
  DiabloDrops:
    BindOnPickup: Legendary, Rare, Unidentified
    BindOnUse: Magical
    BindOnEquip: Set
  EpicBossRecoded:
    BindOnPickup: true
    BindOnUse: false
    BindOnEquip: false
  LoreLocks:
    Bind_Keys: true
  MythicDrops:
    BindOnPickup: common, uncommon, rare
    BindOnUse: terric, netheric
    BindOnEquip: endric